### ISSUE TITLE
Sed "invalid command code ." 

### ISSUE THREAD

**Issue by tabacitu** [shinokada/backpack_install#2]
I tried the script, like it A LOT, had one small issue with the BackupManager and LogManager install and said I’d get back to debug it and… that never happened 😅  Maybe you can provide some insight:

<img width="1018" alt="Screenshot 2021-05-28 at 15 01 40" src="https://user-images.githubusercontent.com/1032474/119983388-c1c1cc80-bfc8-11eb-999a-277ad8b27bf6.png">

This is super weird because yes I do have sed installed:

<img width="445" alt="Screenshot 2021-05-28 at 15 11 45" src="https://user-images.githubusercontent.com/1032474/119983399-c5555380-bfc8-11eb-98a6-cffb2c203020.png">

And the command itself looks… fine! But yeah this sed command errors for me, even when run separately in the terminal:

<img width="747" alt="Screenshot 2021-05-28 at 15 17 40" src="https://user-images.githubusercontent.com/1032474/119983413-cab29e00-bfc8-11eb-80e9-645299697484.png">

Any idea why? Never used sed 🤷‍♂️

Cheers!

PS. Mac OS 11.3.1 (Big Sur) on Apple M1. iTerm & oh-my-zsh

**Comment by tabacitu** [comment]
Well... let me make this even more difficult to debug... 😅 

Ran it a second time, same machine, but this time I ran the one installed with homebrew. And now... it works... 😅🥳🤷‍♂️ Look what I have:

<img width="1429" alt="Screenshot 2021-05-28 at 15 38 35" src="https://user-images.githubusercontent.com/1032474/119985022-ca1b0700-bfca-11eb-828e-6251dede7969.png">

And the command-line output was so nice, it really looked like it knew what it was doing 😅 

<img width="977" alt="Screenshot 2021-05-28 at 15 39 32" src="https://user-images.githubusercontent.com/1032474/119985117-eae35c80-bfca-11eb-8384-8ef9ac1aba86.png">


Excellent work @shinokada !

**Comment by shinokada** [comment]
When you use Homebrew, Homebrew installs dependencies `gsed` which is GNU sed. macOS ships FreeBSD sed and has fewer functionalities. 
That's why when you install it with Homebrew it works.
In the requirements, you can find `gsed` listed.
I will add the details to the README file.

P.S.
Since you used Homebrew installation, you have `gsed` now, so you should be able to install it using the first method you did.

Thank you for trying it out.

**Comment by shinokada** [comment]
Close this for now.
Let me know if you want to reopen.
